### ISSUE TITLE
这个油漆桶填充可不可以做成微信小程序的呢？

### ISSUE THREAD

**Issue by geekxz** [applelee/fast-fill#1]
这个油漆桶填充可不可以做成微信小程序的呢

**Comment by 41421669** [comment]
应该是可以的，但是需要你自己去结合小程序api，把代码搬运过去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈东东"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午4:54
收件人:&nbsp;"applelee/fast-fill"<fast-fill@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[applelee/fast-fill] 这个油漆桶填充可不可以做成微信小程序的呢？ (#1)





 
这个油漆桶填充可不可以做成微信小程序的呢

**Comment by geekxz** [comment]
他的这个dom节点咋搞 ，微信小程序应该没dom节点这么一说？我一个后端不是太懂前端

**Comment by 41421669** [comment]
小程序本质上也是h5



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈东东"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 下午5:04
收件人: "applelee/fast-fill"<fast-fill@noreply.github.com&gt;; 
抄送: "苹果下饭"<41421669@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [applelee/fast-fill] 这个油漆桶填充可不可以做成微信小程序的呢？ (#1)





 
他的这个dom节点咋搞 ，微信小程序应该没dom节点这么一说？我一个后端不是太懂前端

**Comment by geekxz** [comment]
可以加个联系方式不？搞得我头都大了也没转换成功

**Comment by geekxz** [comment]
最近在做一个关于画画的小程序，目前做啦一个简单的画画，想做一个填色的功能

**Comment by 41421669** [comment]
给你一个简单的建议，你可以用小程序的web-view 标签加载外链的h5页面来实现



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈东东"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 下午5:10
收件人: "applelee/fast-fill"<fast-fill@noreply.github.com&gt;; 
抄送: "苹果下饭"<41421669@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [applelee/fast-fill] 这个油漆桶填充可不可以做成微信小程序的呢？ (#1)





 
最近在做一个关于画画的小程序，目前做啦一个简单的画画，想做一个填色的功能

**Comment by geekxz** [comment]
主要是web-view需要资质，个人的没办法。我太难啦
