### ISSUE TITLE
关于fast-fill在vue项目中应用遇到的问题

### ISSUE THREAD

**Issue by njh2001** [applelee/fast-fill#2]
请问老哥，在vue项目中我引用了example中的ff，结构基本一致，只修改了图片路径。 为什么报错找不到画布容器呢？

**Comment by njh2001** [comment]
还有一个bug 相邻区块用了同一个颜色，之后用另一个颜色上色，会将同颜色的全部覆盖

**Comment by 41421669** [comment]
能把报错的截图发下么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "applelee/fast-fill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 晚上8:23
收件人:&nbsp;"applelee/fast-fill"<fast-fill@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[applelee/fast-fill] 关于fast-fill在vue项目中应用遇到的问题 (#2)





 
请问老哥，在vue项目中我引用了example中的ff，结构基本一致，只修改了图片路径。 为什么报错找不到画布容器呢？

**Comment by 41421669** [comment]
发下截图看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "applelee/fast-fill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 晚上8:27
收件人:&nbsp;"applelee/fast-fill"<fast-fill@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [applelee/fast-fill] 关于fast-fill在vue项目中应用遇到的问题 (#2)





 
还有一个bug 相邻区块用了同一个颜色，之后用另一个颜色上色，会将同颜色的全部覆盖

**Comment by njh2001** [comment]
可以留个qq啥的联系方式吗？ github交流太慢了

**Comment by njh2001** [comment]
可以留个qq啥的联系方式吗？ github交流太慢了

**Comment by njh2001** [comment]
![image](https://user-images.githubusercontent.com/56513222/106004032-c2ffed00-60ed-11eb-92a3-1607abc70be2.png)

**Comment by applelee** [comment]
要确保 真实dom 的获取是否成功，可以在mounted回调里查看画布是否顺利渲染

**Comment by njh2001** [comment]
已解决 感谢~
