### ISSUE TITLE
关于在项目中的应用问题

### ISSUE THREAD

**Issue by njh2001** [applelee/fast-fill#4]
我想让一个页面出现多个画板并且分别填色，发现并不可行。创建第二个fastfill实例时，第一个画板会消失。请问如何解决这个问题呢？
id没有重复

**Comment by applelee** [comment]
没有考虑到两个实例的场景，算是一个bug。这两天修复这个问题。

**Comment by applelee** [comment]
已经修复，把最新的代码拉下来可以看到

**Comment by njh2001** [comment]
好的~ 已经解决
