### ISSUE TITLE
 这个微信小程序的版本你搞成功了吗  我看小程序出canvas 2d了 

### ISSUE THREAD

**Issue by geekxz** [applelee/fast-fill#5]
is:issue is:open 这个微信小程序的版本你搞成功了吗  我看小程序出canvas 2d了

**Comment by applelee** [comment]
鉴于大量小程序的使用场景，最近会更新

**Comment by geekxz** [comment]
期待你的更新，你是专门做前端的吗？还是全栈开发呢？

**Comment by 41421669** [comment]
一个普通打工者




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "applelee/fast-fill"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 上午9:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [applelee/fast-fill]  这个微信小程序的版本你搞成功了吗  我看小程序出canvas 2d了  (#5)





 
期待你的更新，你是专门做前端的吗？还是全栈开发呢？

**Comment by geekxz** [comment]
哈哈，打工人打工魂！交个朋友，加个微信吧。我的微信号：geekxz

**Comment by applelee** [comment]
已经更新了小程序例子
